Feature/user delete
SoftonicaDev/softonica-backend pull request #18
Opened 2024-12-27 18:12 UTC by domKul

2024-12-29 20:28 UTC, michupl22 requested changes
- [x] Kiedy loguje się na konto i przekazuje token to endpoint do usuwania jest zablokowany dla użytkownika uwierzytelnionego.
- [x] Jeżeli użytkownik nigdy się nie logował, nie posiada utworzonego profilu lub posiada profil, ale bez żadnych innych danych to usuwamy konto całkowicie.
- [ ] Jeżeli użytkownik logował się i ma utworzony profil to uzupełniamy tylko pole `deleted`.
- [x] Kiedy konto użytkownika jest usunięte to nie można się na nie zalogować.

2025-01-05 20:30 UTC, michupl22 commented
Nadal nie można usunąć konta. Brak wymaganych parametrów.

2025-01-06 16:09 UTC, domKul commented
> Nadal nie można usunąć konta. Brak wymaganych parametrów.

<img width="1408" alt="Zrzut ekranu 2025-01-6 o 17 09 41" src="https://github.com/user-attachments/assets/f7efdef7-158d-415c-82d6-98430043d64e" />

2025-01-12 20:11 UTC, michupl22 requested changes
## Do poprawy

- [ ] Użytkownika usuwamy podając nie nazwę tylko jego unikalny identyfikator, który przeważnie nie będzie znany użytkownikowi.
- [ ] Kiedy użytkownik jest usunięty, ale nie całkowicie z bazy danych to podczas logowania musi być zwrócony komunikat - *Użytkownik został usunięty*. Co oznacza, że dana nazwa użytkownika istnieje i jest zablokowana.
- [x] Kiedy użytkownik w bazie istnieje tylko w tabeli `users` i nie są z nim powiązane żadne dane to usuwamy go całkowicie.

2025-01-22 17:48 UTC, domKul commented
"Użytkownika usuwamy podając nie nazwę tylko jego unikalny identyfikator, który przeważnie nie będzie znany użytkownikowi." co jest tym identifikatorem, jego id ?

2025-02-01 20:15 UTC, michupl22 commented
Podajesz unikalny klucz użytkownika, czyli `id` w bazie danych, który nie jest jawnie pokazywany użytkownikowi, ale po stronie frontendu go się pobiera.

2025-02-02 12:30 UTC, domKul commented
<img width="549" alt="Zrzut ekranu 2025-02-2 o 13 29 56" src="https://github.com/user-attachments/assets/ec0d7cb9-e8e8-462c-b478-f6aaeb3008de" />
teraz jest id i token

2025-02-02 21:03 UTC, michupl22 requested changes
Nie działa usuwanie. Po podaniu identyfikatora i tokenu zwraca odpowiedź 403. Rozwiąż również konflikty łącząc się z gałęzią `develop`.

2025-02-03 20:41 UTC, michupl22 requested changes
Nadal nie działa i to pomimo dodania tokenu zarówno do nagłówka jak i do żądania.

2025-02-17 20:37 UTC, merged